### ISSUE TITLE
custom commands at start etc..

### ISSUE THREAD

**Issue by tectrixdev** [Matistan/MinecraftBlockShuffle#1]
can you create an option in config that takes away player permissions or groups(luckperms) and / or adds them or:
create an option in config to execute a command or commands on start of the gamemode, on stop/ if a player wins, and with placeholders like {playerwhowon}, {players}, {block} and create custom messages

**Comment by Matistan** [comment]
which permissions you want to take away when the game starts?

**Comment by Matistan** [comment]
I'm sorry but I think that these ideas are too specific and I'm not sure if I'm gonna implement this
